menu:
  Home:
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: wusagi24
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:
