menu:
  Home:
  Archives: archives

widgets:
- profile
- recent_posts
- category
- tag

excerpt_link: Read More

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:
